services:
  backend:
    <<: &backend
      image: "backend:dev"
      build:
        context: .
        dockerfile: ./docker/backend/Dockerfile
      ports:
        - 8000:8080
      depends_on:
        - db
      networks:
        - backend-network
    command: runner

  frontend:
    image: "frontend:dev"
    env_file:
      - ./docker/frontend/.env
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - 5173:5173
    networks:
      - backend-network
    command: runner

  db:
    image: "postgres:15.2-alpine"
    env_file:
      - ./docker/db/.env
    volumes:
      - dev_db_data:/var/lib/postgresql/data
      - dev_db_data_backups:/backups
    expose:
      - 5432
    networks:
      - backend-network

volumes:
  dev_db_data: {}
  dev_db_data_backups: {}

networks:
  backend-network:
